CREATE TABLE EVENT_LOG
(
    MESSAGE_ID         SERIAL PRIMARY KEY,
    ENTITY_NAME        VARCHAR(200) NOT NULL,
    ENTITY_KEY         VARCHAR(200) NOT NULL,
    EVENT_PAYLOAD      JSONB NOT NULL,
    MODIFY_TS          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);