# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps): "
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps): "
    groups:
      gha-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps): "
    groups:
      docker-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

#  - package-ecosystem: "terraform"
#    directory: "/terraform"
#    schedule:
#      interval: "weekly"
#    commit-message:
#      prefix: "build(deps): "
#    groups:
#      terraform:
#        patterns:
#          - "*"
#        update-types:
#          - "minor"
#          - "patch"