name: Check feature Workflow
concurrency:
  group: check-and-alpha-tag
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - edited
      - reopened

env:
  TESTCONTAINERS_RYUK_DISABLED: true
permissions:
  contents: write
  id-token: write
  pull-requests: write
  repository-projects: write

jobs:
  check_feature:
    if: ${{ github.event.pull_request.merged == false}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #################################
      ## Go Caching
      #################################

      - name: Set Weekly Cache Key
        id: set-weekly-cache-key
        run: echo "WEEKLY_CACHE_KEY=$(date +%Y-%V)" >> $GITHUB_ENV

      - name: Cache Go build
        id: cache-go-build
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Cache Go modules
        id: cache-go-mod
        uses: actions/cache@v4
        with:
          path: /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache: true
          check-latest: true
          go-version-file: 'go.mod'


      #################################
      ## Build and Test
      #################################

      - name: Build
        run: make build
        env:
          GOMODCACHE: /home/runner/go/pkg/mod
          GOCACHE: /home/runner/.cache/go-build

      - name: Test
        run: make test
        env:
          GOMODCACHE: /home/runner/go/pkg/mod
          GOCACHE: /home/runner/.cache/go-build



  tag_feature:
    needs: check_feature
    if: ${{ github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    concurrency:
      group: tag-feature-group
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump Alpha version
        id: bump_alpha_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: 0.0.0
          RELEASE_BRANCHES: master
          DEFAULT_BRANCH: master
          PRERELEASE_SUFFIX: alpha
          PRERELEASE: true
          BRANCH_HISTORY: last
          DRY_RUN: false
          VERBOSE: true

      # Setting the Build Version
      - name: Set Alpha version environment
        run: |
          echo "ALPHA_VERSION=${{ steps.bump_alpha_version.outputs.new_tag }}" >> $GITHUB_ENV
          echo "ALPHA version ${{ env.ALPHA_VERSION }}"