name: Release Workflow
concurrency:
  group: release-new-feature
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Version bump type (patch, minor, major)'
        required: true
        type: choice
        options:
          - minor
          - major
          - patch
#      custom-tag:
#        description: 'Custom tag to give to this release'
#        required: false
#        default: ''


env:
  TESTCONTAINERS_RYUK_DISABLED: true
permissions:
  contents: write
  id-token: write
  pull-requests: write
  repository-projects: write

jobs:
  release_feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      #################################
      ## Caching
      #################################

      - name: Set Weekly Cache Key
        id: set-weekly-cache-key
        run: echo "WEEKLY_CACHE_KEY=$(date +%Y-%V)" >> $GITHUB_ENV

      - name: Cache Go build
        id: cache-go-build
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Cache Go modules
        id: cache-go-mod
        uses: actions/cache@v4
        with:
          path: /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache: true
          check-latest: true
          go-version-file: 'go.mod'


      #################################
      ## Build and Test
      #################################

      - name: Build
        run: make build
        env:
          GOMODCACHE: /home/runner/go/pkg/mod
          GOCACHE: /home/runner/.cache/go-build

      - name: Test
        run: make test
        env:
          GOMODCACHE: /home/runner/go/pkg/mod
          GOCACHE: /home/runner/.cache/go-build

      #################################
      ## VERSIONING
      #################################
      - name: Bump Release Version
        id: bump_and_tag_release_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.inputs.bump-type }}
          WITH_V: true
          PRERELEASE: false
          INITIAL_VERSION: 0.0.0
          RELEASE_BRANCHES: master
          DEFAULT_BRANCH: master
          TAG_CONTEXT: branch
          BRANCH_HISTORY: compare
          DRY_RUN: false
          VERBOSE: true

      # Setting the Release Version
      - name: Set Release version environment
        run: |
          echo "PREV_RELEASE_VERSION=${{ steps.bump_and_tag_release_version.outputs.old_tag }}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${{ steps.bump_and_tag_release_version.outputs.new_tag }}" >> $GITHUB_ENV


      #################################
      ## CHANGELOG AND RELEASE
      #################################
      - name: Generate Changelog
        id: generate_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/release-changelog-config.json"
          fromTag: ${{ env.PREV_RELEASE_VERSION }}
          toTag: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}