name: Check feature Workflow
concurrency:
  group: check-and-alpha-tag
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      pull_request_commits:
        required: true
        type: number
      pull_request_head_sha:
        required: true
        type: string
      pull_request_base_sha:
        required: true
        type: string

env:
  TESTCONTAINERS_RYUK_DISABLED: true
permissions:
  contents: write
  id-token: write
  pull-requests: write
  repository-projects: write

jobs:
  check_feature:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: $(${{ inputs.pull_request_commits }} + 1)
          ref: ${{ inputs.pull_request_head_sha }}
          fetch-tags: false

      #################################
      ## Go Caching
      #################################

      - name: Set Weekly Cache Key
        id: set-weekly-cache-key
        run: echo "WEEKLY_CACHE_KEY=$(date +%Y-%V)" >> $GITHUB_ENV

      - name: Cache Go build
        id: cache-go-build
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go', '**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Cache Go modules
        id: cache-go-mod
        uses: actions/cache@v4
        with:
          path: /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache: true
          check-latest: true
          go-version-file: 'go.mod'


      #################################
      ## Build and Test
      #################################

      - name: Build
        run: make build
        env:
          GOMODCACHE: /home/runner/go/pkg/mod
          GOCACHE: /home/runner/.cache/go-build

      - name: Test
        run: make test
        env:
          GOMODCACHE: /home/runner/go/pkg/mod
          GOCACHE: /home/runner/.cache/go-build